### ISSUE TITLE
Taking so much processing time

### ISSUE THREAD

**Issue by 0x416c69** [dolfinus/AutoSitemap#15]
When I want to edit or add a page, AutoSitemap takes 70seconds to process.

These are my settings:
```php
$wgAutoSitemap["notify"] = [
    'https://www.google.com/webmasters/sitemaps/ping?sitemap=https://wiki.arsacia.ir/sitemap.xml',
    'https://www.bing.com/webmaster/ping.aspx?sitemap=https://wiki.arsacia.ir/sitemap.xml'
];

$wgAutoSitemap["filename"] = "sitemap.xml";
```

MediaWiki Version: 1.34
PHP Version: 7.2.24 (litespeed)
MySQL Version: 5.5.62-0ubuntu0.14.04.1

Latest AutoSitemap files on master branch.

**Comment by dolfinus** [comment]
Sitemap is being generated on any page create/update/rename/delete. After any of these events is raised, it executes SQL query to get all pages should be added to sitemap, and time of such query execution increases with increasing page count.

How many pages in your wiki do you have?

There are few ways to decrease query execution time:
- Add namespace with non-important pages to exclusion list using option `$wgAutoSitemap["exclude_namespaces"]`
- Add non-important page names to exclusion list using option `$wgAutoSitemap["exclude_pages"]`
- Disable priority calculation based on revisions count with setting option `$wgAutoSitemap["freq"]` to any supported value excluding `adjust` (default)

**Comment by 0x416c69** [comment]
I have 131 pages and I believe that it's not even close to being considered a lot. I also have powerful hardware.

Isn't there some sort of caching? Does AutoSitemap compute and recalculate all pages on a single page edit/add/delete/rename? Well if that's the case, there goes this extension's problem.

**Comment by dolfinus** [comment]
"Does AutoSitemap compute and recalculate all pages on a single page edit/add/delete/rename?"
Yes, of course.

There is no explicit caching of pages the result can be wrong. Cache should be used to only if you have rarely changing data like MW settings or if data is being stored in cache only for seconds. Otherwise you can get errors because some data is not exist anymore or was updated in master source  but not in the cache.
Sitemap is not like any of these options so some kind of static class variable or memcached as cache cannot be used here.

But you can improve this behavior using OPCache. If this extension is enabled in PHP, it takes less time to parse and execute code, to sitemap will be generated faster without any issues caused by frequently updated data.

I use [PHP 7.3.12, MySQL 5.7.21 and MW 1.30.0](https://en.crystalls.info/Special:Version) on shared hosting, and it takes about 3 seconds to generate sitemap for more than 2000 pages.
The real execution time is even less than that because I also use [PhpTags extension](https://www.mediawiki.org/wiki/Extension:PhpTags) which parses and executes php tags in pages content in a sandbox, and it executes on every page change too.

Actually, I quite surprised that generating sitemap for such a small amount of pages takes so long time.

**Comment by 0x416c69** [comment]
I'm not much of a MW expert, but I don't think we're talking about the same kind of cache.

Obviously, when a page content updates in the database, it reminds the way it is until it gets updated again.

And sitemap is just a file and writing to a file is FAST, it could be the MySQL server responding too late or there's much of computation. You should build a file for every page in the sitemap and regenerate that file only when it's updated. (Or create/delete when it's created/deleted)

And then combine and compile the sitemap from those files instead. (Or just use a new table instead of file storage)

Looking at your code there's no transaction or no caching.

**Comment by dolfinus** [comment]
"And then combine and compile the sitemap from those existing data instead."
You can contribute another scheme of generating sitemap and then we can check which way is better.
