### ISSUE TITLE
Sitemap index files aren't supported.

### ISSUE THREAD

**Issue by TaylanUB** [dolfinus/AutoSitemap#32]
The [sitemap protocol](https://www.sitemaps.org/protocol.html) says that a sitemap file is limited to 50,000 URLs and 50 MB file size.

If the limits are exceeded, one must create a "sitemap index" file in place of the regular sitemap, which links to a number of regular sitemap files that each honor the limits.

I'm creating this issue just to note that this isn't supported at the moment by this extension. I don't know if I'll try to implement it at some point, or if we even really need it.

**Comment by Fredrilj** [comment]
Hi Taylan,

I have a site that is near the limit of 50,000 articles/URLs. Would greatly
appreciate it if someone with insight into AutoSitemap and knowledge of
PHP/XSLT would try to fix this.

Thanks,
Fredrik

tir. 31. jan. 2023 kl. 23:37 skrev Taylan Kammer ***@***.***>:

**Comment by dolfinus** [comment]
Hi.

If Mediawiki instance contains so much pages that sitemap exceeds the limit, then not only the file format should be changed, but also the way this sitemap is generated - for example, generate sitemap file on schedule (every day or several hours) instead of generating it after every page create/update/delete/rename/etc.

Current extension does not support that. Instead someone can use [GenerateSitemap.php](https://www.mediawiki.org/wiki/Manual:GenerateSitemap.php) maintenance script which already generates a sitemap index file as well as separated sitemap files for each namespace, with compression support. This script is already designed to be executed on schedule.

**Comment by Fredrilj** [comment]
Thank you for the reply and suggestions.

Fredrik

tir. 7. feb. 2023, 19:37 skrev Maxim Martynov ***@***.***>:
